# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.BuildDate={{ .CommitDate }}
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "darwin" }}Darwin
      {{- else if eq .Arch "linux" }}Linux
      {{- else if eq .Arch "windows" }}Windows
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  # build latest and specific tag version images
  - image_templates:
      - "ghcr.io/linode-obs/{{.ProjectName}}:{{ .Tag }}"
      - "ghcr.io/linode-obs/{{.ProjectName}}:latest"
    goos: linux
    goarch: amd64
    use: docker
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source=https://github.com/linode-obs/nagios_exporter"
    - "--label=org.opencontainers.image.description='A Prometheus Exporter for Nagios'"
    - "--label=org.opencontainers.image.licenses=MIT"
nfpms:
  -  id: default
     formats:
      - deb
      - rpm
     package_name: "prometheus-nagios-exporter"
     section: "default"
     priority: "extra"
     replaces: []
     dependencies: []
     recommends: []
     suggests: []
     conflicts: []
     maintainer: "Will Bollock <wbollock@gmail.com>"
     description: |
       A Prometheus Nagios Exporter that provides information
       on the current state of a Nagios application and configuration.
     homepage: "https://github.com/linode-obs/nagios_exporter"
     license: "MIT"
     # TODO - changelog?
     #changelog: "changelog.yaml"
     contents:
     # provided by goreleaser
     - src: ./dist/nagios_exporter_linux_amd64_v1/nagios_exporter
       dst: /usr/local/bin/prometheus-nagios-exporter
     - src: ./nfpm/etc/config.toml
       dst: /etc/prometheus-nagios-exporter/config.toml
       type: config
     - src: ./nfpm/systemd/prometheus-nagios-exporter.service
       dst: /etc/systemd/system/prometheus-nagios-exporter.service
       type: config
     - src: ./nfpm/etc/default/prometheus-nagios-exporter
       dst: /etc/default/prometheus-nagios-exporter
       type: config
     scripts:
        postinstall: ./nfpm/scripts/postinstall.sh
