{
 "title": "Nagios Exporter",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": "nagios" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(nagios_up{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(nagios_version_info{instance=\"$instance\", job=\"$job\"},version)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nagios_up", "legendFormat": "{{ legend }}" }
   ]
  },
  {
   "title": "Service Status",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nagios_services_status_total{job=\"$job\", instance=\"$instance\", status=\"ok\"}",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "nagios_services_status_total{job=\"$job\", instance=\"$instance\", status=\"warn\"}",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "nagios_services_status_total{job=\"$job\", instance=\"$instance\", status=\"critical\"}",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "nagios_services_status_total{job=\"$job\", instance=\"$instance\", status=\"flapping\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Check Types for Services",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nagios_services_checked_total{job=\"$job\", instance=\"$instance\", check_type=\"active\"}",
     "legendFormat": "{{check_type}}"
    },
    {
     "expr": "nagios_services_checked_total{job=\"$job\", instance=\"$instance\", check_type=\"passive\"}",
     "legendFormat": "{{check_type}}"
    }
   ]
  },
  {
   "title": "Percent of Down Services Acknowledged",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(nagios_services_acknowledges_total{job=\"$job\", instance=\"$instance\"} / ignoring(status) (nagios_services_status_total{job=\"$job\", instance=\"$instance\", status=\"critical\"} + ignoring(status) nagios_services_status_total{job=\"$job\", instance=\"$instance\", status=\"unknown\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percent of Warning Services Acknowledged",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(nagios_services_acknowledges_total{job=\"$job\", instance=\"$instance\"} / ignoring(status) (nagios_services_status_total{job=\"$job\", instance=\"$instance\", status=\"warn\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flapping Services",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nagios_services_status_total{job=\"$job\", instance=\"$instance\", status=\"flapping\"}",
     "legendFormat": "Services"
    }
   ]
  },
  {
   "title": "Nagios Version",
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "options": {
    "content": "<center><h1>${version}</h1></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Host Status",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nagios_hosts_status_total{job=\"$job\", instance=\"$instance\", status=\"up\"}",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "nagios_hosts_status_total{job=\"$job\", instance=\"$instance\", status=\"down\"}",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "nagios_hosts_status_total{job=\"$job\", instance=\"$instance\", status=\"unreachable\"}",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "nagios_hosts_status_total{job=\"$job\", instance=\"$instance\", status=\"flapping\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Check Types for Hosts",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nagios_hosts_checked_total{job=\"$job\", instance=\"$instance\", check_type=\"active\"}",
     "legendFormat": "{{check_type}}"
    },
    {
     "expr": "nagios_hosts_checked_total{job=\"$job\", instance=\"$instance\", check_type=\"passive\"}",
     "legendFormat": "{{check_type}}"
    }
   ]
  },
  {
   "title": "Percent of Down Hosts Acknowledged",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(nagios_hosts_acknowledges_total{job=\"$job\", instance=\"$instance\"} / ignoring(status) (nagios_hosts_status_total{job=\"$job\", instance=\"$instance\", status=\"down\"} + ignoring(status) nagios_hosts_status_total{job=\"$job\", instance=\"$instance\", status=\"unreachable\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flapping Hosts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nagios_hosts_status_total{job=\"$job\", instance=\"$instance\", status=\"flapping\"}",
     "legendFormat": "Hosts"
    }
   ]
  },
  { "title": "Hosts and Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Total Number of Hosts and Services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "nagios_services_total{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Services"
    },
    {
     "expr": "nagios_hosts_total{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Hosts"
    }
   ]
  },
  {
   "title": "Total Number",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nagios_services_total{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Services"
    },
    {
     "expr": "nagios_hosts_total{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Hosts"
    }
   ]
  },
  {
   "title": "Downtime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nagios_services_downtime_total{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Services"
    },
    {
     "expr": "nagios_hosts_downtime_total{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Hosts"
    }
   ]
  },
  {
   "title": "Services - OK",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nagios_services_status_total{job=\"$job\", instance=\"$instance\", status=\"ok\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Services - Warn",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nagios_services_status_total{job=\"$job\", instance=\"$instance\", status=\"warn\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Services - Critical",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nagios_services_status_total{job=\"$job\", instance=\"$instance\", status=\"critical\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Services - Unknown",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nagios_services_status_total{job=\"$job\", instance=\"$instance\", status=\"unknown\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hosts - Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nagios_hosts_status_total{job=\"$job\", instance=\"$instance\", status=\"up\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hosts - Down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nagios_hosts_status_total{job=\"$job\", instance=\"$instance\", status=\"down\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hosts - Unreachable",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nagios_hosts_status_total{job=\"$job\", instance=\"$instance\", status=\"unreachable\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "nagios_services_status_total{job=\"$job\", instance=\"$instance\", status=\"ok\"}",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "nagios_services_status_total{job=\"$job\", instance=\"$instance\", status=\"warn\"}",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "nagios_services_status_total{job=\"$job\", instance=\"$instance\", status=\"critical\"}",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "nagios_services_status_total{job=\"$job\", instance=\"$instance\", status=\"flapping\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Host Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "nagios_hosts_status_total{job=\"$job\", instance=\"$instance\", status=\"up\"}",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "nagios_hosts_status_total{job=\"$job\", instance=\"$instance\", status=\"down\"}",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "nagios_hosts_status_total{job=\"$job\", instance=\"$instance\", status=\"unreachable\"}",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "nagios_hosts_status_total{job=\"$job\", instance=\"$instance\", status=\"flapping\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Checks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Host Checks Ran Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "nagios_host_checks_minutes_bucket{job=\"$job\", instance=\"$instance\",check_type=\"active\"}",
     "legendFormat": "{{check_type}} - {{le}} minutes"
    },
    {
     "expr": "nagios_host_checks_minutes_bucket{job=\"$job\", instance=\"$instance\",check_type=\"passive\"}",
     "legendFormat": "{{check_type}} - {{le}} minutes"
    }
   ]
  },
  {
   "title": "Service Checks Ran Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 30 },
   "targets": [
    {
     "expr": "nagios_service_checks_minutes_bucket{job=\"$job\", instance=\"$instance\",check_type=\"active\"}",
     "legendFormat": "{{check_type}} - {{le}} minutes"
    },
    {
     "expr": "nagios_service_checks_minutes_bucket{job=\"$job\", instance=\"$instance\",check_type=\"passive\"}",
     "legendFormat": "{{check_type}} - {{le}} minutes"
    }
   ]
  },
  {
   "title": "Average Check Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nagios_host_checks_performance_seconds{job=\"$job\", instance=\"$instance\",check_type=\"active\", performance_type=\"execution\", operator=\"avg\"}",
     "legendFormat": "Host - {{operator}} {{performance_type}}"
    },
    {
     "expr": "nagios_service_checks_performance_seconds{job=\"$job\", instance=\"$instance\",check_type=\"active\", performance_type=\"execution\", operator=\"avg\"}",
     "legendFormat": "Service - {{operator}} {{performance_type}}"
    }
   ]
  },
  {
   "title": "Average Check Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nagios_host_checks_performance_seconds{job=\"$job\", instance=\"$instance\",check_type=\"active\", performance_type=\"latency\", operator=\"avg\"}",
     "legendFormat": "Host - {{operator}} {{performance_type}}"
    },
    {
     "expr": "nagios_service_checks_performance_seconds{job=\"$job\", instance=\"$instance\",check_type=\"active\", performance_type=\"latency\",operator=\"avg\"}",
     "legendFormat": "Service - {{operator}} {{performance_type}}"
    }
   ]
  },
  {
   "title": "Check Types for Hosts and Services",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "nagios_services_checked_total{job=\"$job\", instance=\"$instance\", check_type=\"active\"}",
     "legendFormat": "{{check_type}} - services"
    },
    {
     "expr": "nagios_hosts_checked_total{job=\"$job\", instance=\"$instance\", check_type=\"passive\"}",
     "legendFormat": "{{check_type}} - hosts"
    },
    {
     "expr": "nagios_services_checked_total{job=\"$job\", instance=\"$instance\", check_type=\"passive\"}",
     "legendFormat": "{{check_type}} - services"
    },
    {
     "expr": "nagios_hosts_checked_total{job=\"$job\", instance=\"$instance\", check_type=\"active\"}",
     "legendFormat": "{{check_type}} - hosts"
    }
   ]
  },
  {
   "title": "Services Critical/Unknown vs Check Types",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 39 },
   "targets": [
    {
     "expr": "nagios_services_checked_total{job=\"$job\", instance=\"$instance\", check_type=\"passive\"}",
     "legendFormat": "{{check_type}}"
    },
    {
     "expr": "nagios_services_checked_total{job=\"$job\", instance=\"$instance\", check_type=\"active\"}",
     "legendFormat": "{{check_type}}"
    },
    {
     "expr": "nagios_services_status_total{job=\"$job\", instance=\"$instance\", status=\"critical\"}",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "nagios_services_status_total{job=\"$job\", instance=\"$instance\", status=\"unknown\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Hosts Down/Unreachable vs Check Types",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 39 },
   "targets": [
    {
     "expr": "nagios_hosts_checked_total{job=\"$job\", instance=\"$instance\", check_type=\"passive\"}",
     "legendFormat": "{{check_type}}"
    },
    {
     "expr": "nagios_hosts_checked_total{job=\"$job\", instance=\"$instance\", check_type=\"active\"}",
     "legendFormat": "{{check_type}}"
    },
    {
     "expr": "nagios_hosts_status_total{job=\"$job\", instance=\"$instance\", status=\"down\"}",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "nagios_hosts_status_total{job=\"$job\", instance=\"$instance\", status=\"unreachable\"}",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}